### ISSUE TITLE
Extract each lesson into a separate file

### ISSUE THREAD

**Issue by ignasxv** [ignasxv/master-of-education#39]
Let's have three folders under lessons, And each lesson stands in its own .tsx file
- Math 
- Physics
- Other

**Comment by Heracraft** [comment]
simply why? we'll import the components the same way so why?

**Comment by ignasxv** [comment]
> simply why? we'll import the components the same way so why?

It's a good convention to separate Objects (in this case components) into their own separate files -at least in most languages. 

Unless they have a two-way association? 

Ofcz For now it doesn't make so much difference... but as the number of lessons grow It might become quite unsustainable to maintain and even makes it more likely to create impure components. 

What do you think?

**Comment by Heracraft** [comment]
True, I was thinking within the next 4 days

**Comment by ignasxv** [comment]
Greatyi greatyi, you can put this issue on hold then... 
and we will revisit it when it's necessary 🍻
